### ISSUE TITLE
Include option of No of Games a user wants to play

### ISSUE THREAD

**Issue by 97shivank** [97shivank/RockPaperScissor#3]
try to include options of asking no of game an user want to play with computer at startup.

**Comment by ghost** [comment]
HI!!! I am Aritra Sen a first year b.tech student of IIT Kharagpur.

**Comment by ghost** [comment]
I have some ideas in my mind, which might help:
1. The usual random functions use mersenne twin prng, not CS random number generation. So, it becomes visible, for say, if a robot plays this game,it can predict it's next outcome, so better to use SystemRandom(), which provides you with cryptographically safe random number generation.
2. This is a total deviation: What if  we, 

- Provided a audio wave file saying stone paper scissor, then await for the file to reach it's end then activate the buttons, which actually have the hand sign logos, the computer showing it's choice of photo, the user gives it's click to a button of his choice, and if the response is within 250 ms, we get the corresponding score or else consider it a late call, and then score accordingly, and then ask for another round or quit?

**Comment by ghost** [comment]
Please reply if you liked my idea, I will work accordingly :)

**Comment by 97shivank** [comment]
Hello Aritra,
1- yes it is good idea of using SystemRandom(),try to implement it.
2-okay, this idea also sounds cool Aritra,you can work on it and ping me on slack if you stuck anywhere.
